### ISSUE TITLE
Right way for inherit class

### ISSUE THREAD

**Issue by thankjura** [GodotNativeTools/godot-cpp#122]
How to create base class with register property/methods and inherit it?
what I want:
bullet.hpp:

> class Bullet: public RigidBody2D {
>protected:
> double _DAMAGE;
> .......
> }

bullet.cpp:

> void Bullet::_register_methods() {
>     register_property("main/damage", &Bullet::_DAMAGE,  double(100));
> }

rocket.hpp:
> class Rocket: public Bullet {
> GODOT_CLASS (Rocket, RigidBody2D);
> .......
> }

But I do not see "main/damage" property in editor.

And how to check class type. 

> _collision(Object* obj) {
>     Bullet* b = as<Bullet>(obj);
>     if (b) {} // always true
> }

**Comment by karroffel** [comment]
I think that's an error with the macro.

https://github.com/GodotNativeTools/godot-cpp/blob/nativescript-1.1/include/core/Godot.hpp#L43

This should probably be changed to use `___get_type_name` instead.

**Comment by BastiaanOlij** [comment]
GODOT_SUBCLASS is a macro that allows you to 'subclass' a GDNative class from another GDNative class.
Have a look at: https://github.com/BastiaanOlij/gdprocmesh
All the nodes that make up the graph are subclasses of gdprocnode so you can see the difference between the two.

Closing this as the issue was resolved long ago :)
