### ISSUE TITLE
_notification override doesn't work?

### ISSUE THREAD

**Issue by xDGameStudios** [GodotNativeTools/godot-cpp#252]
I tried this:

```
void Vertex::_notification(int64_t p_what) {
	Godot::print("Notification");
	switch(p_what) {
		case NOTIFICATION_PREDELETE:
			Godot::print("Deleting");
			break;
	}
}
```

nothing gets printed to editor output. Is this a bug?!

**Comment by karroffel** [comment]
This should work if you register the `_notification` method.

**Comment by xDGameStudios** [comment]
> This should work if you register the `_notification` method.

@karroffel well, I tried registering it and still nothing happens... `Vertex` is  Reference in this case and I'm trying to detect the `NOTIFICATION_PREDELETE `.

**Comment by karroffel** [comment]
I am not sure why that is happening, but I think the `NOTIFICATION_PREDELETE` is not guaranteed to reach the script, because it might be removed before the object gets actually deallocated.

In that case you can put functionality into the destructor of your class, the destructor should always be called (unless you are leaking instances)

**Comment by xDGameStudios** [comment]
my methods create instances of `Reference` through GDNative...
for example `graph.add_vertex()` creates a `Vertex`... could be something wrong with it?!
what is the correct way to instantiate an object from GDNative c++...

I'm using `MyClass::_new()`

**Comment by xDGameStudios** [comment]
the _notifications were not being called because creating `Reference` via C++ needs a special workaround... related with #253
