### ISSUE TITLE
Reference design question

### ISSUE THREAD

**Issue by Zylann** [GodotNativeTools/godot-cpp#80]
I'm a bit confused reading the way this is handled in code, please tell me if I'm wrong:

Currently, the C++ binding for `Reference` encapsulates a `godot_object`, right.

Now, let's say you create a `Resource` in GDScript which will hold 1 reference. Then you pass that `Resource` to a `NativeScript`, which will create a `Resource` wrapper on the heap and hold a 2nd reference.

But what happens if you unref that wrapper?
Two choices:

1) You `delete` it, which will also call `godot::api->godot_object_destroy` on the `Resource`, which is pretty bad given the refcount may not be zero (due to the var being also in GDScript)

2) The current option: you don't `delete` the wrapper, call unref() normally and let the object leave... which however leaves you with a **leaking `godot::Resource` wrapper on the heap**.

BUT...
Is that leak avoided by the fact classes actually don't "wrap" a pointer, but in fact **ARE the pointer?** I see `this` is casted to `godot_object`... which means, if the ref doesn't reach zero, Godot will free the memory. And if ref reaches zero, the C++ bindings will free it?
O.O

**Comment by karroffel** [comment]
So yeah, as you've already figured out, the wrappers don't wrap on a data level, they just wrap on an interface level.

Allocating heap data is not necessary since the pointer is all you need and actually that this points never gets accessed directly from C++. All methods are non-virtual, so no vtable needed etc, it all works out.

It's just a nice class-shaped interface-wrapper around the Godot given pointer.

The bindings never do any reference keeping (AFAIK), so it all comes from Godot. IIRC the C interface doesn't do anything special with references either, so the problem probably is in the ptrcall implementation somewhere?

**Comment by sheepandshepherd** [comment]
The original Godot classes do, but we can't access the vtable from GDNative since we don't know its layout. In GDNative code, a `Object *` in reality points to an instance of the *original* `Object` class from Godot core.

That's also why the GDNative Object "wrapper" class can't have virtual methods -- the wrong vtable would be accessed when they're called.

**Comment by BastiaanOlij** [comment]
Is this still valid now this has been redesigned in Nativescript 1.1?

**Comment by BastiaanOlij** [comment]
I'll close this for now as well, as there has been no discussion since January and a lot has changed in Nativescript 1.1 around references. Thanks all!
