### ISSUE TITLE
Purpose of Read/Write inner classes

### ISSUE THREAD

**Issue by lupoDharkael** [GodotNativeTools/godot-cpp#95]
As @karroffel mentioned in the last progress report, we have 2 new inner classes in PoolArray's API created in this commit https://github.com/GodotNativeTools/godot-cpp/commit/e3b20a28a93c35ef33865d2f05ba6ac82fc170ae

What's the purpose of these classes? I think it should be commented on top of the header or documented somewhere. If it is, could you please link me that information.

**Comment by karroffel** [comment]
PoolArrays need to be locked in order to write or read from them. By using `set` or the index operator on a PoolArray this locking happens automatically. But this also means that when you use those to access and modify the data that there's a lot of overhead due to the constant locking and unlocking.

The Read and Write access objects lock the PoolArray when they are created and unlock automatically when they get leave the scope.

So they are used to get better performance when accessing data in blocks.

set/get way:
```cpp
// p is a PoolIntArray
for (int i = 0; i < p.size(); i++) {
    printf("%d ", p[i]); // p[i] will lock and unlock - every iteration
}
```

read way:
```cpp
{
    auto read = p.read(); // locking happens here

    for (int i = 0; i < p.size(); i++) {
        printf("%d ", read[i]); // just plain access, almost no overhead
    }

} // unlocking happens here
```

**Comment by BastiaanOlij** [comment]
As this has been explained, closing :)
